---
linters:
  phpcs:
    standard: CakePHP
    extensions: 'php,ctp'
    fixer: true

fixers:
  enable: true
  workflow: commit

review:
    # Don't use 'failure' build status when
    # a pull request contains style errors.
    fail_on_comments: false