language: php

branches:
  only:
  - master

dist: trusty

sudo: false

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

script: phpunit

before_script:
    - composer install